aws:
  accountId: AWS_ACCOUNT_ID
  region: AWS_REGION
  s3:
    bucket: COMMANDS_S3_BUCKET
    prefix: COMMANDS_S3_PREFIX
    roleArn: COMMANDS_S3_ROLE_ARN
  iot:
    endpoint: COMMANDS_IOT_ENDPOINT
  jobs:
    maxTargets: COMMAND_JOBS_MAXTARGETS

tmpdir: COMMANDS_TMPDIR

tables:
  templates: COMMANDS_TABLES_TEMPLATES
  jobs: COMMANDS_TABLES_JOBS

mqtt:
  topics:
    presigned: COMMANDS_MQTT_TOPICS_PRESIGNED

cors:
  origin: COMMANDS_CORS_ORIGIN

templates:
  addThingToGroup: COMMANDS_TEMPLATES_ADDTHINGTOGROUP

assetLibrary:
  apiFunctionName: COMMANDS_ASSETLIBRARY_APIFUNCTIONNAME
provisioning:
  apiFunctionName: COMMANDS_PROVISIONING_APIFUNCTIONNAME

logging:
  level: COMMANDS_LOGGING_LEVEL



