aws:
  region: AWS_REGION
  accountId: AWS_ACCOUNT_ID
  s3:
    roleArn: CDF_PROVISIONING_S3_ROLEARN
    templates:
      bucket: CDF_PROVISIONING_S3_TEMPLATES_BUCKET
      prefix: CDF_PROVISIONING_S3_TEMPLATES_PREFIX
      suffix: CDF_PROVISIONING_S3_TEMPLATES_SUFFIX
    certificates:
      bucket: CDF_PROVISIONING_S3_CERTIFICATES_BUCKET
      prefix: CDF_PROVISIONING_S3_CERTIFICATES_PREFIX
    bulkrequests:
      bucket: CDF_PROVISIONING_S3_BULKREQUESTS_BUCKET
      prefix: CDF_PROVISIONING_S3_BULKREQUESTS_PREFIX
events:
  certificatesBatch:
    topic: CDF_PROVISIONING_EVENTS_CERTIFICATESBATCH_TOPIC
features:
  delete:
    deleteCertificates: CDF_PROVISIONING_FEATURES_DELETE_CERTIFICATES
    deletePolicies: CDF_PROVISIONING_FEATURES_DELETE_POLICIES
deviceCertificateExpiryDays: BULKCERTS_CERTEXPIRY
cors:
  origin: CDF_PROVISIONING_CORS_ORIGIN

logging:
  level: CDF_PROVISIONING_LOGGING_LEVEL


