aws:
  region: AWS_REGION
  accountId: AWS_ACCOUNT_ID
sqs:
  requestQueue:
    queueUrl: REQUESTQUEUE_REQUEST_QUEUE_URL
  dlqQueue:
    queueUrl: REQUESTQUEUE_DLQ_QUEUE_URL
primary:
  healthCheckUrl: REQUESTQUEUE_PRIMARY_HEALTH_CHECK_URL
  healthCheckResponse: REQUESTQUEUE_PRIMARY_HEALTH_CHECK_RESPONSE
  apiLambdaArn: REQUESTQUEUE_PRIMARY_API_LAMBDA_ARN
cdf:
  mimeType: REQUESTQUEUE_CDF_MIME_TYPE
  allowedMethods: REQUESTQUEUE_CDF_ALLOWED_METHODS
cors:
  origin: REQUESTQUEUE_CORS_ORIGIN

logging:
  level: REQUESTQUEUE_LOGGING_LEVEL


