aws:
  region:
  accountId:

sqs:
  requestQueue:
    queueUrl:
    replayBatchSize:
  dlqQueue:
    queueUrl:

lambda:
  stopLambdaAtRemainingMillis:

primary:
  healthCheckUrl:
  healthCheckResponse:
  apiLambdaArn:

cdf:
  mimeType:
  allowedMethods:

cors:
  origin:

logging:
  level: debug


  