# semantic-release config

plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/npm':
  - '@semantic-release/git':
    assets: 
      - dist/**/*
      - '**/*/package.json'
      - '**/*/package-lock.json'
      - 'shrinkwrap.json'
    message: 'chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}'