aws:
  accountId:
  region:

  ssm:
    managedInstanceRole:

  sqs:
    agentlessDeploymentQueue:
    agentbasedDeploymentQueue:

  dynamoDB:
    ggProvisioningTable:

  s3:
    deploymentLogs:
      bucket:
      prefix:

cors:
  origin:
  exposedHeaders: content-type,location

supportedApiVersions:
  - json:
      - '1.0'

logging:
  level: debug
