aws:
  accountId: AWS_ACCOUNT_ID
  region: AWS_REGION
  s3:
    certificates:
      bucket: BULKCERTS_AWS_S3_CERTIFICATES_BUCKET
      prefix: BULKCERTS_AWS_S3_CERTIFICATES_PREFIX
  dynamodb:
    tasks:
      tableName: BULKCERTS_AWS_DYNAMODB_TASKS_TABLE
  
events:
  request:
    topic:  BULKCERTS_EVENTS_REQUEST_TOPIC

cors:
  origin: BULKCERTS_CORS_ORIGIN

deviceCertificateInfo:
  commonName: BULKCERTS_DEVICECERTIFICATEINFO_COMMONNAME
  organization: BULKCERTS_DEVICECERTIFICATEINFO_ORGANIZATION
  organizationalUnit: BULKCERTS_DEVICECERTIFICATEINFO_ORGANIZATIONALUNIT
  locality: BULKCERTS_DEVICECERTIFICATEINFO_LOCALITY
  stateName: BULKCERTS_DEVICECERTIFICATEINFO_STATENAME
  country: BULKCERTS_DEVICECERTIFICATEINFO_COUNTRY
  emailAddress: BULKCERTS_DEVICECERTIFICATEINFO_EMAILADDRESS
  distinguishedNameQualifier: BULKCERTS_DEVICECERTIFICATEINFO_DISTINGUISHEDNAMEQUALIFIER
  serialNumber: BULKCERTS_DEVICECERTIFICATEINFO_SERIALNUMBER
  id: BULKCERTS_DEVICECERTIFICATEINFO_ID

supplierRootCa:
  bosch: BULKCERTS_SUPPLIERROOTCA_BOSCH

deviceCertificateExpiryDays: BULKCERTS_CERTEXPIRY

defaults:
  chunkSize: BULKCERTS_DEFAULTS_CHUNKSIZE

logging:
  level: BULKCERTS_LOGGING_LEVEL

