aws:
  accountId: 
  region: 

  dynamodb:
    tasks:
      tableName: 
  s3:
    certificates:
      bucket: 
      prefix:

events:
  request:
    topic: 

deviceCertificateInfo:
  commonName:
  organization:
  organizationalUnit:
  locality:
  stateName:
  country:
  emailAddress:
  distinguishedNameQualifier: '?'

deviceCertificateExpiryDays: 365

supplierRootCa:
  bosch:

cors:
  origin:
  exposedHeaders: content-type,location

defaults:
  chunkSize: 100

supportedApiVersions:
  - json:
      - '1.0'

logging:
  level: debug

