neptuneUrl: ASSETLIBRARY_NEPTUNE_URL
aws:
  region: AWS_REGION
  iot:
    endpoint: AWS_IOT_ENDPOINT
    
events:
  groups:
    topic: ASSETLIBRARY_GROUPS_TOPIC
  devices:
    topic: ASSETLIBRARY_DEVICES_TOPIC
  policies:
    topic: ASSETLIBRARY_POLICIES_TOPIC
  groupTemplates:
    topic: ASSETLIBRARY_GROUPTEMPLATES_TOPIC
  deviceTemplates:
    topic: ASSETLIBRARY_DEVICETEMPLATES_TOPIC
  profiles:
    topic: ASSETLIBRARY_PROFILES_TOPIC

defaults:
  devices:
    parent:
      relation: ASSETLIBRARY_DEFAULTS_DEVICES_PARENT_RELATION
      groupPath: ASSETLIBRARY_DEFAULTS_DEVICES_PARENT_GROUPPATH
    state: ASSETLIBRARY_DEFAULTS_DEVICES_STATE
  groups:
    validateAllowedParentPaths: ASSETLIBRARY_DEFAULTS_GROUPS_VALIDATEALLOWEDPARENTPATHS

cors:
  origin: ASSETLIBRARY_CORS_ORIGIN

mode: ASSETLIBRARY_MODE

cache:
  types:
    ttl: ASSETLIBRARY_CACHE_TYPES_TTL

authorization:
  enabled: ASSETLIBRARY_AUTHORIZATION_ENABLED

logging:
  level: ASSETLIBRARY_LOGGING_LEVEL
