Type: AWS::IAM::Role
Properties:
  AssumeRolePolicyDocument:
    Version: "2012-10-17"
    Statement:
      -
        Effect: "Allow"
        Principal:
          Service:
            - "apigateway.amazonaws.com"
        Action:
          - sts:AssumeRole
  Policies:
    -
      PolicyName: "InvokeAuthorizerFunction"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Action:
              - lambda:InvokeAsync
              - lambda:InvokeFunction
            Resource:
              Ref: AuthorizerFunctionArn
