Type: AWS::Serverless::Api
Properties:
  StageName: Prod
  EndpointConfiguration: REGIONAL
  Auth:
    Authorizers:
      LambdaTokenAuth:
        FunctionPayloadType: TOKEN
        FunctionArn:
          Ref: AuthorizerFunctionArn
        FunctionInvokeRole:
          Fn::GetAtt:
            - ApiGatewayAuthorizerInvokeRole
            - Arn
    DefaultAuthorizer: LambdaTokenAuth
