provisioning:
  baseUrl: CDF_PROVISIONING_BASEURL
  headers: CDF_PROVISIONING_HEADERS
  mode: CDF_PROVISIONING_CLIENT_MODE
  apifunctionname: CDF_PROVISIONING_API_FUNCTION_NAME

logging:
  level: CDF_PROVISIONING_LOGGING_LEVEL
