
provisioning:
  baseUrl: CDF_PROVISIONING_BASEURL
  headers: CDF_PROVISIONING_HEADERS
  mode: CDF_PROVISIONING_MODE
  apiFunctionName: CDF_PROVISIONING_APIFUNCTIONNAME

logging:
  level: CDF_PROVISIONING_LOGGING_LEVEL
