greengrassDeployment:
  baseUrl: CDF_GREENGRASS_DEPLOYMENT_BASEURL
  headers: CDF_GREENGRASS_DEPLOYMENT_HEADERS
  mode: CDF_GREENGRASS_DEPLOYMENT_MODE
  apiFunctionName: CDF_GREENGRASS_DEPLOYMENT_APIFUNCTIONNAME

logging:
  level: CDF_GREENGRASS_DEPLOYMENT_LOGGING_LEVEL
