aws:
  region: AWS_REGION
  s3:
    crl:
      bucket: CERTIFICATEACTIVATOR_AWS_S3_CRL_BUCKET
      key: CERTIFICATEACTIVATOR_AWS_S3_CRL_KEY

assetLibrary:
  baseUrl:  CERTIFICATEACTIVATOR_ASSETLIBRARY_BASEURL
  templateProfiles:
    edge: CERTIFICATEACTIVATOR_ASSETLIBRARY_TEMPLATEPROFILES_EDGE
provisioning:
  baseUrl:  CERTIFICATEACTIVATOR_PROVISIONING_BASEURL
