aws:
  region: AWS_REGION
  s3:
    crl:
      bucket: CERTIFICATEACTIVATOR_AWS_S3_CRL_BUCKET
      key: CERTIFICATEACTIVATOR_AWS_S3_CRL_KEY

assetLibrary:
  apiFunctionName:  CERTIFICATEACTIVATOR_ASSETLIBRARY_APIFUNCTIONNAME
  templateProfiles:
    edge: CERTIFICATEACTIVATOR_ASSETLIBRARY_TEMPLATEPROFILES_EDGE
provisioning:
  apiFunctionName:  CERTIFICATEACTIVATOR_PROVISIONING_APIFUNCTIONNAME

logging:
  level: CERTIFICATEACTIVATOR_LOGGING_LEVEL

