#--------------------------------------------------------------------------------
# Copyright (c) 2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# This source code is subject to the terms found in the AWS Enterprise Customer Agreement.
#---------------------------------------------------------------------------------
bulkcerts:
  baseUrl: CDF_BULKCERTS_BASEURL
  headers: CDF_BULKCERTS_HEADERS
  mode: CDF_BULKCERTS_MODE
  apiFunctionName: CDF_BULKCERTS_APIFUNCTIONNAME


logging:
  level: debug
