#--------------------------------------------------------------------------------
# Copyright (c) 2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# This source code is subject to the terms found in the AWS Enterprise Customer Agreement.
#---------------------------------------------------------------------------------
bulkcerts:
  baseUrl:
  headers:
  mode:
  apiFunctionName:


logging:
  level: debug
