aws:  
  region: AWS_REGION
  iot:
    thingName: AWS_IOT_THINGNAME
    keyPath: AWS_IOT_KEYPATH
    certPath: AWS_IOT_CERTPATH
    caPath: AWS_IOT_CAPATH
    endpointAddress: AWS_IOT_ENDPOINTADDRESS

calculations:
  interval: CALCULATIONS_INTERVAL

logging:
  level: LOGGING_LEVEL
