.variables:
  variables: 
    ENVIRONMENT:
      value: 
      description: 
    CONFIG_ENVIRONMENT:
      value: 
      description: 
    INFRASTRUCTURE_PROJECT:
      value: 
      description: 
    KEY_PAIR_NAME:
      value: 
      description: 
    BASTION_REMOTE_ACCESS_CIDR:
      value: 
      description: 
    DEPLOY_ARTIFACTS_STORE_BUCKET:
      value: 
      description: 
    KMS_KEY_ID:
      value: 
      description: 
    API_GATEWAY_AUTH:
      value: 
      description: 
    TEMPLATE_SNIPPET_S3_URI_BASE:
      value: 
      description: 
    API_GATEWAY_DEFINITION_TEMPLATE:
      value: 
      description: 
    COGNTIO_USER_POOL_ARN:
      value: 
      description: 
    AUTHORIZER_FUNCTION_ARN:
      value: 
      description: 
    ASSETLIBRARY_MODE:
      value: 
      description: 
    USE_EXISTING_VPC:
      value: 
      description: 
    VPC_ID:
      value: 
      description: 
    SOURCE_SECURITY_GROUP_ID:
      value: 
      description: 
    PRIVATE_SUBNET_IDS:
      value: 
      description: 
    PUBLIC_SUBNET_IDS:
      value: 
      description: 
    PRIVATE_ROUTE_TABLE_IDS:
      value: 
      description: 
