#-----------------------------------------------------------------------------------------------------------------------
#   Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License"). You may not use this file except in compliance
#  with the License. A copy of the License is located at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  or in the 'license' file accompanying this file. This file is distributed on an 'AS IS' BASIS, WITHOUT WARRANTIES
#  OR CONDITIONS OF ANY KIND, express or implied. See the License for the specific language governing permissions
#  and limitations under the License.
#-----------------------------------------------------------------------------------------------------------------------
aws:
  region: AWS_REGION
  iot:
    endpoint: AWS_IOT_ENDPOINT
  neptune:
    url: ASSETLIBRARY_AWS_NEPTUNE_URL
    enableDfeOptimization: ASSETLIBRARY_AWS_NEPTUNE_ENABLEDFEOPTIMIZATION

events:
  groups:
    topic: ASSETLIBRARY_GROUPS_TOPIC
  devices:
    topic: ASSETLIBRARY_DEVICES_TOPIC
  policies:
    topic: ASSETLIBRARY_POLICIES_TOPIC
  groupTemplates:
    topic: ASSETLIBRARY_GROUPTEMPLATES_TOPIC
  deviceTemplates:
    topic: ASSETLIBRARY_DEVICETEMPLATES_TOPIC
  profiles:
    topic: ASSETLIBRARY_PROFILES_TOPIC

defaults:
  devices:
    parent:
      relation: ASSETLIBRARY_DEFAULTS_DEVICES_PARENT_RELATION
      groupPath: ASSETLIBRARY_DEFAULTS_DEVICES_PARENT_GROUPPATH
    state: ASSETLIBRARY_DEFAULTS_DEVICES_STATE
  groups:
    validateAllowedParentPaths: ASSETLIBRARY_DEFAULTS_GROUPS_VALIDATEALLOWEDPARENTPATHS

cors:
  origin: ASSETLIBRARY_CORS_ORIGIN
  exposedHeaders: ASSETLIBRARY_CORS_EXPOSEDHEADERS

mode: ASSETLIBRARY_MODE

cache:
  types:
    ttl: ASSETLIBRARY_CACHE_TYPES_TTL

authorization:
  enabled: ASSETLIBRARY_AUTHORIZATION_ENABLED

logging:
  level: ASSETLIBRARY_LOGGING_LEVEL

customDomain:
  basePath: ASSETLIBRARY_CUSTOMDOMAIN_BASEPATH
