aws:
  accountid:
  region:
assetLibrary:
  baseUrl:
assetLibraryHistory:
  baseUrl:
commands:
    baseUrl:
    thing:
      arn:
provisioning:
  baseUrl:
  templates:
    bucket:
    prefix:
    suffix:
