aws:
  accountid:
  region:
  sns:
    push_gcm:
      platformApplicationArn:
assetLibrary:
  baseUrl:
assetLibraryHistory:
  baseUrl:
commands:
  baseUrl:
greengrassProvisioning:
  baseUrl:
provisioning:
  baseUrl:
  templates:
    bucket:
    prefix:
    suffix:
greengrassDeployment:
  baseUrl:

notifications:
  baseUrl:
thing:
  name:
  arn:
logging:
  level: debug
