aws:
  region: AWS_REGION 

  dynamoDb:
    tables: 
      events: ASSETLIBRARYHISTORY_AWS_DYNAMODB_TABLES_EVENTS

cors:
  origin: ASSETLIBRARYHISTORY_CORS_ORIGIN
  exposedHeaders: ASSETLIBRARYHISTORY_CORS_EXPOSEDHEADERS

logging:
  level: ASSETLIBRARYHISTORY_LOGGING_LEVEL
