aws:
  region: AWS_REGION
  iot:
    endpoint: AWS_IOT_ENDPOINT

  dynamoDb:
    tables:
      eventConfig:
        name: EVENTSPROCESSOR_AWS_DYNAMODB_TABLES_EVENTCONFIG_NAME
        gsi1: EVENTSPROCESSOR_AWS_DYNAMODB_TABLES_EVENTCONFIG_GSI1
        gsi2: EVENTSPROCESSOR_AWS_DYNAMODB_TABLES_EVENTCONFIG_GSI2
      eventNotifications:
        name: EVENTSPROCESSOR_AWS_DYNAMODB_TABLES_EVENTNOTIFICATIONS_NAME
        gsi1: EVENTSPROCESSOR_AWS_DYNAMODB_TABLES_EVENTNOTIFICATIONS_GSI1

    dax:
      endpoints: EVENTSPROCESSOR_AWS_DYNAMODB_DAX_ENDPOINTS
  
  lambda:
    dynamoDbStream:
      name: EVENTSPROCESSOR_AWS_LAMBDA_DYNAMODBSTREAM_NAME

cors:
  origin: EVENTSPROCESSOR_CORS_ORIGIN
