aws:
  region: 
  iot:
    endpoint:

  dynamoDb:
    tables:
      eventNotifications:
        name: MUST_SET!
        gsi1: gsiBucket-gsi1Sort-index  
  
  lambda:
    dynamoDbStream:
      name: MUST_SET!
