#-------------------------------------------------------------------------------
# Copyright (c) 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# This source code is subject to the terms found in the AWS Enterprise Customer Agreement.
#-------------------------------------------------------------------------------
aws:
  region: 
  iot:
    endpoint:

  dynamoDb:
    tables:
      eventConfig:
        name: MUST_SET!
        gsi1: sk-gsi1Sort-index
      eventNotifications:
        name: MUST_SET!
        gsi1: gsiBucket-gsi1Sort-index

    dax:
      endpoints:
  
  lambda:
    dynamoDbStream:
      name: MUST_SET!

logging:
  level: debug

