greengrassProvisioning:
  baseUrl: CDF_GREENGRASS_PROVISIONING_BASEURL
  headers: CDF_GREENGRASS_PROVISIONING_HEADERS
  mode: CDF_GREENGRASS_PROVISIONING_MODE
  apiFunctionName: CDF_GREENGRASS_PROVISIONING_APIFUNCTIONNAME

logging:
  level: CDF_GREENGRASS_PROVISIONING_LOGGING_LEVEL
