openapi: 3.0.0
info:
  title: "Connected Device Framework: Device Simulator"
  version: 2.0.0
  
  
tags:
  - name: Plans
    description: >
      TODO
  - name: Simulations
    description: >
      TODO
  - name: Runs
    description: >
      TODO
      
paths:
  "/simulations":
    post:
      tags:
        - Simulations
      summary: Creates a new simulation definition.
      operationId: createSimulation
      requestBody:
        required: true
        content:
          application/vnd.aws-cdf-v1.0+json:
            schema:
              $ref: "#/components/schemas/SimulationDetail"
      responses:
        "201":
          $ref: "#/components/responses/Created"
        "400":
          $ref: "#/components/responses/BadRequest"
    get:
      tags:
        - Simulations
      summary: Lists all defined simulations.
      operationId: listSimulations
      responses:
        "200":
          description: OK
          content:
            application/vnd.aws-cdf-v1.0+json:
              schema:
                $ref: "#/components/schemas/SimulationList"


  "/simulations/{simulationId}":
    parameters:
      - $ref: '#/components/parameters/simulationId'

    get:
      tags:
        - Simulations
      summary: Returns a specific simulation.
      operationId: getSimulation
      responses:
        "200":
          description: OK
          content:
            application/vnd.aws-cdf-v1.0+json:
              schema:
                $ref: "#/components/schemas/SimulationDetail"
        "404":
          $ref: "#/components/responses/NotFound"
    patch:
      tags:
        - Simulations
      summary: Update an existing simulation.
      operationId: updateSimulation
      requestBody:
        required: true
        content:
          application/vnd.aws-cdf-v1.0+json:
            schema:
              $ref: "#/components/schemas/SimulationDetail"
      responses:
        "204":
          description: OK
        "400":
          $ref: "#/components/responses/BadRequest"
        "404":
          $ref: "#/components/responses/NotFound"
    delete:
      tags:
        - Simulations
      summary: Deletes an existing simulation.
      operationId: deleteSimulation
      responses:
        "204":
          description: OK
        "400":
          $ref: "#/components/responses/BadRequest"
        "404":
          $ref: "#/components/responses/NotFound"
          
          
  "/simulations/{simulationId}/runs":
    parameters:
      - $ref: '#/components/parameters/simulationId'
    post:
      tags:
        - Runs
      summary: Creates a new run of a given simulation.
      operationId: createRun
      requestBody:
        required: true
        content:
          application/vnd.aws-cdf-v1.0+json:
            schema:
              $ref: "#/components/schemas/RunDetail"
      responses:
        "201":
          $ref: "#/components/responses/Created"
        "400":
          $ref: "#/components/responses/BadRequest"
    get:
      tags:
        - Runs
      summary: Lists all runs for a given simulation.
      operationId: listRuns
      responses:
        "200":
          description: OK
          content:
            application/vnd.aws-cdf-v1.0+json:
              schema:
                $ref: "#/components/schemas/RunList"
        "404":
          $ref: "#/components/responses/NotFound"  
          
          
  "/simulations/{simulationId}/runs/{runId}":
    parameters:
      - $ref: '#/components/parameters/simulationId'
      - $ref: '#/components/parameters/runId'
    get:
      tags:
        - Runs
      summary: Returns a specific run for a given simulation.
      operationId: getRun
      responses:
        "200":
          description: OK
          content:
            application/vnd.aws-cdf-v1.0+json:
              schema:
                $ref: "#/components/schemas/RunDetail"
        "404":
          $ref: "#/components/responses/NotFound"  
    patch:
      tags:
        - Runs
      summary: Updates a specific run for a given simulation.
      operationId: patchRun
      requestBody:
        required: true
        content:
          application/vnd.aws-cdf-v1.0+json:
            schema:
              $ref: "#/components/schemas/RunDetail"
      responses:
        "204":
          description: OK
          content:
            application/vnd.aws-cdf-v1.0+json:
              schema:
                $ref: "#/components/schemas/RunDetail"
        "404":
          $ref: "#/components/responses/NotFound"   
    delete:
      tags:
        - Runs
      summary: Deletes a specific run for a given simulation.
      operationId: deleteRun
      responses:
        "204":
          description: OK
        "404":
          $ref: "#/components/responses/NotFound"  
          
  
  
  "/plans":
    post:
      tags:
        - Plans
      summary: Creates a new simulation plan.
      operationId: createPlan
      requestBody:
        required: true
        content:
          application/vnd.aws-cdf-v1.0+json:
            schema:
              $ref: "#/components/schemas/PlanDetail"
      responses:
        "201":
          $ref: "#/components/responses/Created"
        "400":
          $ref: "#/components/responses/BadRequest"
    get:
      tags:
        - Plans
      summary: Lists all defined plans..
      operationId: listPlans
      responses:
        "200":
          description: OK
          content:
            application/vnd.aws-cdf-v1.0+json:
              schema:
                $ref: "#/components/schemas/PlanList"


  "/plans/{planId}":
    parameters:
      - $ref: '#/components/parameters/planId'

    get:
      tags:
        - Plans
      summary: Returns a specific simulation plan.
      operationId: getPlan
      responses:
        "200":
          description: OK
          content:
            application/vnd.aws-cdf-v1.0+json:
              schema:
                $ref: "#/components/schemas/PlanDetail"
        "404":
          $ref: "#/components/responses/NotFound"
    patch:
      tags:
        - Plans
      summary: Update an existing plan.
      operationId: updatePlan
      requestBody:
        required: true
        content:
          application/vnd.aws-cdf-v1.0+json:
            schema:
              $ref: "#/components/schemas/PlanDetail"
      responses:
        "204":
          description: OK
        "400":
          $ref: "#/components/responses/BadRequest"
        "404":
          $ref: "#/components/responses/NotFound"
    delete:
      tags:
        - Plans
      summary: Deletes an existing simulation plan.
      operationId: deletePlan
      responses:
        "204":
          description: OK
        "400":
          $ref: "#/components/responses/BadRequest"
        "404":
          $ref: "#/components/responses/NotFound"
          
          
components:
  schemas:
    SimulationSummary:
      properties:
        id:
          type: string
          description: Unique id of the simulation
        name:
          type: string
          description: Human friendly name
        description:
          type: string
          description: Description
      required:
        - name
          
    SimulationDetail:
      allOf:
        - $ref: '#/components/schemas/SimulationSummary'
        - type: object
          properties:
            planId:
              type: string
              description: ID of simulation plan.
        
    SimulationList:
      properties:
        results:
          description: A list of simulations.
          type: array
          items:
            $ref: '#/components/schemas/SimulationSummary'
            
    RunSummary:
      properties:
        id:
          type: string
        name:
          type: string
      required:
        - name
          
    RunDetail:
      allOf:
        - $ref: '#/components/schemas/RunSummary'
        - type: object
        
    RunList:
      properties:
        results:
          description: A list of simulations runs.
          type: array
          items:
            $ref: '#/components/schemas/RunSummary'
            
    PlanSummary:
      properties:
        id:
          type: string
        name:
          type: string
      required:
        - name
          
    PlanDetail:
      allOf:
        - $ref: '#/components/schemas/PlanSummary'
        - type: object
        
    PlanList:
      properties:
        results:
          description: A list of simulations plans.
          type: array
          items:
            $ref: '#/components/schemas/PlanSummary'
            
    Error:
      type: object
      properties:
        message:
          description: Error message
          type: string
   
  parameters:
    simulationId:
      name: simulationId
      in: path
      description: ID of simulation.
      required: true
      schema:
        type: string
    runId:
      name: runId
      in: path
      description: ID of simulation run.
      required: true
      schema:
        type: string
            
  responses:         
    Created:
      description: Created successfully
      headers:
        location:
          description:  URI of the created resource
          schema:
            type: string        
    Deleted:
      description: Deleted successfully
    BadRequest:
      description: Invalid input
      content:
        application/vnd.aws-cdf-v1.0+json:
          schema:
            $ref: '#/components/schemas/Error'
    NotFound:
      description: Not found
      content:
        application/vnd.aws-cdf-v1.0+json:
          schema:
            $ref: '#/components/schemas/Error'
    Unauthorized:
      description: Unauthorized
      content:
        application/vnd.aws-cdf-v1.0+json:
          schema:
            $ref: '#/components/schemas/Error'

          