#-----------------------------------------------------------------------------------------------------------------------
#   Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License"). You may not use this file except in compliance
#  with the License. A copy of the License is located at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  or in the 'license' file accompanying this file. This file is distributed on an 'AS IS' BASIS, WITHOUT WARRANTIES
#  OR CONDITIONS OF ANY KIND, express or implied. See the License for the specific language governing permissions
#  and limitations under the License.
#-----------------------------------------------------------------------------------------------------------------------
AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: CDF OpenSSL Lambda Layer

Parameters:
  Environment:
    Description:  Name of environment.  Used to name the created resources.
    Type: String
    MinLength: 1

Resources:

  OpenSslLamdaLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: cdf-openssl
      Description: "CDF: OpenSSL"
      ContentUri: ../build/build.zip
      CompatibleRuntimes:
        - nodejs16.x
        - python3.8
        - java11
      RetentionPolicy: Delete

Outputs:
  LayerVersionArn:
    Description: Layer Version ARN
    Value: !Ref OpenSslLamdaLayer
    Export: 
      Name: !Sub "cdf-openssl-${Environment}-LayerVersionArn"
