site_name: Connected Device Framework (CDF)
use_directory_urls: false

nav:
  - Start: index.md
  - Overview: projects/overview.md
  - Tracks:
    - Beginner: beginner/index.md
    - Intermediate: intermediate/index.md
    - Advanced: advanced/index.md
  - Projects:
    - Asset Library:
      - 'Overview': projects/assetlibrary/overview.md
      - 'Modes': projects/assetlibrary/modes.md
      - 'Templates (User)': projects/assetlibrary/templates-user.md
      - 'Templates (Developer)': projects/assetlibrary/templates-developer.md
      - 'Events': projects/assetlibrary/events.md
      - 'Swagger': projects/assetlibrary/assetlibrary-swagger.md
      - 'Profiles': projects/assetlibrary/profiles.md
      - 'Fine-Grained Access Control': projects/assetlibrary/fine-grained-access-control.md
      - 'Configuration': projects/assetlibrary/configuration.md
    - Asset Library History:
      - 'Overview': projects/assetlibrary-history/overview.md
      - 'Swagger': projects/assetlibrary-history/assetlibraryhistory-swagger.md
    - Bulk Certs:
      - 'Overview' : projects/bulkcerts/overview.md
      - 'Swagger': projects/bulkcerts/bulkcerts-swagger.md
    - Certificate Activator:
      - 'Overview' : projects/certificateactivator/overview.md
    - Certificate Vendor:
      - 'Overview' : projects/certificatevendor/overview.md
    - Commands:
      - 'Overview' : projects/commands/overview.md
      - 'Pre-signed Urls (User)' : projects/commands/presigned-urls-user.md
      - 'Pre-signed Urls (Developer)' : projects/commands/presigned-urls-developer.md
      - 'Ephemeral Groups' : projects/commands/ephemeral-groups.md
      - 'Swagger': projects/commands/commands-swagger.md
    - Custom Device Authorizer:
      - 'Overview' : projects/auth-devicecert/overview.md
    - Device Monitoring:
      - 'Overview' : projects/devicemonitoring/overview.md
    - Facade:
        - 'CDF Demo Overview': projects/facade/overview.md
        - 'CDF Auto Facade (CMS) Overview': projects/facade/facade-auto.md
    - Notifications:
      - 'Overiew' : projects/notifications/overview.md
      - 'Walkthrough' : projects/notifications/walkthrough.md
      - 'Design' : projects/notifications/design.md
      - 'Swagger': projects/notifications/events-processor-swagger.md
    - Provisioning:
      - Overview: projects/provisioning/overview.md
      - Templates: projects/provisioning/provisioning-templates.md
      - Swagger: projects/provisioning/provisioning-swagger.md
    - Greengrass Provisioning:
      - Overview: projects/greengrass-provisioning/overview.md
      - Design: projects/greengrass-provisioning/design.md
      - Swagger: projects/greengrass-provisioning/greengrass-provisioning-swagger.md
    - Greengrass Deployment:
      - Overview: projects/greengrass-deployment/overview.md
      - Design: projects/greengrass-deployment/design.md
      - Swagger: projects/greengrass-deployment/greengrass-deployment-swagger.md
    - Request Queue:
      - Overview : projects/request-queue/overview.md
    - Reusable Libraries:
      - Overview : projects/libraries/README.md
  - User:
    - Postman: postman/index.md
  - Development:
    - 'Getting Started': development/quickstart.md 
    - 'Prerequisites': development/prerequisites.md
    - 'Tech Stack': development/tech-stack.md
    - 'Dependency Injection': development/dependency-injection.md
    - 'Asynchronous Programming': development/async.md
    - 'Config': development/config.md
    - 'Unit Testing': development/unit-testing.md
    - 'Integration Testing': development/integration-testing.md
  - Admin:
    - 'Deployment': advanced/deployment.md
    - 'Releases': releases/releases.md
    - 'CI/CD': advanced/cicd.md

plugins:
  - search
#  - pdf-export:
#      enabled_if_env: ENABLE_PDF_EXPORT
#      combined: true
#      combined_output_path: pdf/cdf.pdf

theme:
  name: 'material'

markdown_extensions:
  - markdown.extensions.admonition:
  - markdown_include.include:
      base_path: docs
  - pymdownx.emoji:
  - pymdownx.details:
  - pymdownx.mark:
  - pymdownx.superfences:
  - toc:
      permalink: True
