aws:
  accountId: AWS_ACCOUNT_ID
  region: AWS_REGION

  dynamoDb:
    table: GREENGRASS_PROVISIONING_AWS_DYNAMODB_TABLE

  greengrass:
    bulkdeployments:
      roleArn: GREENGRASS_PROVISIONING_AWS_GREENGRASS_BULKDEPLOYMENTS_ROLEARN

  iot:
    endpoint: GREENGRASS_PROVISIONING_AWS_IOT_ENDPOINT

  s3:
    artifacts:
      bucket: GREENGRASS_PROVISIONING_AWS_S3_ARTIFACTS_BUCKET
      prefix: GREENGRASS_PROVISIONING_AWS_S3_ARTIFACTS_PREFIX

  sqs:
    deviceAssociations: GREENGRASS_PROVISIONING_AWS_SQS_DEVICEASSOCIATIONS
    deployments: GREENGRASS_PROVISIONING_AWS_SQS_DEPLOYMENTS
    bulkDeploymentsStatus: GREENGRASS_PROVISIONING_AWS_SQS_BULKDEPLOYMENTSSTATUS
    deploymentStatus: GREENGRASS_PROVISIONING_AWS_SQS_DEPLOYMENTSTATUS
    groupTasks: GREENGRASS_PROVISIONING_AWS_SQS_GROUPTASKS
    
cors:
  origin: GREENGRASS_PROVISIONING_CORS_ORIGIN
  exposedHeaders: GREENGRASS_PROVISIONING_CORS_EXPOSEDHEADERS

provisioning:
  mode: GREENGRASS_PROVISIONING_PROVISIONING_MODE
  apiFunctionName: GREENGRASS_PROVISIONING_PROVISIONING_APIFUNCTIONNAME

logging:
  level: GREENGRASS_PROVISIONING_LOGGING_LEVEL

defaults:
  promisesConcurrency: GREENGRASS_PROVISIONING_DEFAULTS_PROMISESCONCURRENCY
  groupBatchSize: GREENGRASS_PROVISIONING_DEFAULTS_GROUP_BATCH_SIZE
 
