aws:
  accountId:
  region:

  dynamoDb:
    table:

  greengrass:
    bulkdeployments:
      roleArn:
      
  iot:
    endpoint:

  s3:
    artifacts:
      bucket: 
      prefix:

    bulkdeployments:
      bucket: 
      prefix:

  sqs:
    deviceAssociations:
    deployments:
    bulkDeploymentsStatus:
    deploymentStatus:
    groupTasks:

cors:
  origin:
  exposedHeaders: content-type,location

provisioning:
  apiFunctionName:
  mode: 'lambda'

supportedApiVersions:
  - json:
      - '1.0'

logging:
  level: debug

defaults:
  promisesConcurrency: 10
  groupBatchSize: 20

