aws:
  accountId:
  region:

  dynamoDb:
    table:

  greengrass:
    bulkdeployments:
      roleArn:
      
  iot:
    endpoint:

  s3:
    artifacts:
      bucket: 
      prefix:

    bulkdeployments:
      bucket: 
      prefix:

  sqs:
    deviceAssociations:
    deployments:
    bulkDeploymentsStatus:
    deploymentStatus:

cors:
  origin:

provisioning:
  apifunctionname:
  mode: 'lambda'

supportedApiVersions:
  - json:
      - '1.0'

logging:
  level: debug
